//
//  HikingSpot.swift
//  Hiking Planner
//
//  Created by MacBook Air on 21.06.24.
//

import Foundation

// MARK: - Transport Type Model
struct TransportType: Identifiable {
    let id = UUID()
    let name: String
    let description: String
    let image: String
    let levels: [Level]
}

// MARK: - Level Model
struct Level: Identifiable {
    let id = UUID()
    let name: String
    let description: String
    let image: String
    let hikingSpots: [HikingSpot]
}

// MARK: - Hiking Spot Model
struct HikingSpot: Identifiable {
    let id = UUID()
    let name: String
    let location: String
    let description: String
    let tips: String
    let thingsToTake: String
    let travelTime: String
    let additionalInfo: String
    let video: String
    let image: String
    let rating: Double
}

// MARK: - Hiking Data / Transport Type Data / Hiking Spot Data
struct HikingSampleData {
    static let transportTypes: [TransportType] = [
        TransportType(name: "Car", description: "Drive to the hiking spots", image: "https://i.pinimg.com/564x/76/0e/65/760e65d1bfe1f7c98a58dc6e374dab65.jpg", levels: [
            Level(name: "Easy Trails", description: "Perfect for beginners", image: "https://i.pinimg.com/564x/56/21/80/562180eaafdf00e796425a41653f3de3.jpg", hikingSpots: [
                HikingSpot(name: "Lakeside Path", location: "Lake District", description: "A serene path by the lake. Enjoy a tranquil walk along the lake, surrounded by beautiful scenery and wildlife. Ideal for families and beginner hikers.", tips: "Bring water and snacks. Wear comfortable shoes.", thingsToTake: "Water, snacks, hat, sunscreen.", travelTime: "2 hours", additionalInfo: "Best time to visit is early morning or late afternoon.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Beachside Trail", location: "Beachside Park", description: "A refreshing walk by the beach. Breathe in the fresh ocean air as you stroll along the sandy shores, perfect for a relaxed and scenic hike.", tips: "Watch out for high tides. Bring a camera for stunning views.", thingsToTake: "Water, snacks, beach towel, camera.", travelTime: "1.5 hours", additionalInfo: "Best visited during low tide for easier access.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.8),
                HikingSpot(name: "Lakeside Path", location: "Lake District", description: "A serene path by the lake. Enjoy a tranquil walk along the lake, surrounded by beautiful scenery and wildlife. Ideal for families and beginner hikers.", tips: "Bring water and snacks. Wear comfortable shoes.", thingsToTake: "Water, snacks, hat, sunscreen.", travelTime: "2 hours", additionalInfo: "Best time to visit is early morning or late afternoon.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Beachside Trail", location: "Beachside Park", description: "A refreshing walk by the beach. Breathe in the fresh ocean air as you stroll along the sandy shores, perfect for a relaxed and scenic hike.", tips: "Watch out for high tides. Bring a camera for stunning views.", thingsToTake: "Water, snacks, beach towel, camera.", travelTime: "1.5 hours", additionalInfo: "Best visited during low tide for easier access.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.8),
                HikingSpot(name: "Lakeside Path", location: "Lake District", description: "A serene path by the lake. Enjoy a tranquil walk along the lake, surrounded by beautiful scenery and wildlife. Ideal for families and beginner hikers.", tips: "Bring water and snacks. Wear comfortable shoes.", thingsToTake: "Water, snacks, hat, sunscreen.", travelTime: "2 hours", additionalInfo: "Best time to visit is early morning or late afternoon.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Beachside Trail", location: "Beachside Park", description: "A refreshing walk by the beach. Breathe in the fresh ocean air as you stroll along the sandy shores, perfect for a relaxed and scenic hike.", tips: "Watch out for high tides. Bring a camera for stunning views.", thingsToTake: "Water, snacks, beach towel, camera.", travelTime: "1.5 hours", additionalInfo: "Best visited during low tide for easier access.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.8)
                
            ]),
            Level(name: "Medium Trails", description: "Moderate difficulty for intermediate hikers", image: "https://i.pinimg.com/564x/17/b2/52/17b252f965f81c806c8281cbfffb7a29.jpg", hikingSpots: [
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6)
            ]),
            Level(name: "Hard Trails", description: "Challenging trails for experienced hikers", image: "https://i.pinimg.com/564x/9c/21/67/9c2167a527ef354c3f7a75ea6bfe6931.jpg", hikingSpots: [
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2),
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2),
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2)
            ])
        ]),
        TransportType(name: "Walk", description: "Walk to the hiking spots", image: "https://images.pexels.com/photos/211047/pexels-photo-211047.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", levels: [
            Level(name: "Easy Trails", description: "For intermediate hikers", image: "https://i.pinimg.com/564x/56/21/80/562180eaafdf00e796425a41653f3de3.jpg", hikingSpots: [
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6)
            ]),
            Level(name: "Medium Trails", description: "For intermediate hikers", image: "https://i.pinimg.com/564x/17/b2/52/17b252f965f81c806c8281cbfffb7a29.jpg", hikingSpots: [
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6)
            ]),
            Level(name: "Hard Trails", description: "For intermediate hikers", image: "https://i.pinimg.com/564x/9c/21/67/9c2167a527ef354c3f7a75ea6bfe6931.jpg", hikingSpots: [
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Forest Walk", location: "Greenwood Forest", description: "A peaceful walk through the forest. Explore the lush greenery and diverse flora as you hike through this serene forest trail.", tips: "Stay on marked trails. Watch for wildlife.", thingsToTake: "Water, snacks, insect repellent, map.", travelTime: "3 hours", additionalInfo: "Best visited in the morning to avoid heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.3),
                HikingSpot(name: "Hilltop Hike", location: "Hilltop Park", description: "A challenging hike to the hilltop. Reward yourself with breathtaking views after a strenuous climb to the top of the hill.", tips: "Pace yourself and take breaks. Carry extra water.", thingsToTake: "Water, snacks, hat, trekking poles.", travelTime: "4 hours", additionalInfo: "Avoid during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6)
            ])
        ]),
        TransportType(name: "Bike", description: "Bike to the hiking spots", image: "https://images.pexels.com/photos/161172/cycling-bike-trail-sport-161172.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", levels: [
            Level(name: "Easy Trails", description: "For experienced hikers", image: "https://i.pinimg.com/564x/56/21/80/562180eaafdf00e796425a41653f3de3.jpg", hikingSpots: [
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2),
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2),
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2)
            ]),
            Level(name: "Medium Trails", description: "For experienced hikers", image: "https://i.pinimg.com/564x/17/b2/52/17b252f965f81c806c8281cbfffb7a29.jpg", hikingSpots: [
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2),
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2),
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2)
            ]),
            Level(name: "Hard Trails", description: "For experienced hikers", image: "https://i.pinimg.com/564x/9c/21/67/9c2167a527ef354c3f7a75ea6bfe6931.jpg", hikingSpots: [
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2),
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2),
                HikingSpot(name: "Mountain Trail", location: "Rocky Mountains", description: "A beautiful mountain trail. Navigate through rugged terrain and enjoy stunning mountain vistas along this demanding trail.", tips: "Start early to avoid afternoon storms. Wear layers.", thingsToTake: "Water, snacks, layered clothing, first aid kit.", travelTime: "6 hours", additionalInfo: "Check weather conditions before heading out.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.7),
                HikingSpot(name: "Desert Trek", location: "Sahara Desert", description: "An adventurous trek through the desert. Experience the unique beauty of the desert landscape on this challenging and exciting trek.", tips: "Carry plenty of water. Protect yourself from the sun.", thingsToTake: "Water, snacks, sunscreen, hat, sunglasses.", travelTime: "5 hours", additionalInfo: "Best avoided during midday heat.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.2)
            ])
        ]),
        TransportType(name: "Horse", description: "Ride a horse to the hiking spots", image: "https://i.pinimg.com/564x/56/21/80/562180eaafdf00e796425a41653f3de3.jpg", levels: [
            Level(name: "Easy Trails", description: "Enjoy horseback riding trails", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", hikingSpots: [
                HikingSpot(name: "Valley Ride", location: "Sunny Valley", description: "A scenic valley ride. Traverse through beautiful valleys and enjoy the serene environment on horseback.", tips: "Ensure your horse is well-fed and hydrated.", thingsToTake: "Water, snacks, hat, horse feed.", travelTime: "3 hours", additionalInfo: "Best enjoyed in the cooler hours of the day.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Hilltop Gallop", location: "Highland Hills", description: "A gallop to the hilltop. Experience the thrill of horseback riding while enjoying panoramic views from the hilltop.", tips: "Wear comfortable riding gear. Bring extra water.", thingsToTake: "Water, snacks, riding gear, camera.", travelTime: "2.5 hours", additionalInfo: "Best to start early in the morning.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Valley Ride", location: "Sunny Valley", description: "A scenic valley ride. Traverse through beautiful valleys and enjoy the serene environment on horseback.", tips: "Ensure your horse is well-fed and hydrated.", thingsToTake: "Water, snacks, hat, horse feed.", travelTime: "3 hours", additionalInfo: "Best enjoyed in the cooler hours of the day.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Hilltop Gallop", location: "Highland Hills", description: "A gallop to the hilltop. Experience the thrill of horseback riding while enjoying panoramic views from the hilltop.", tips: "Wear comfortable riding gear. Bring extra water.", thingsToTake: "Water, snacks, riding gear, camera.", travelTime: "2.5 hours", additionalInfo: "Best to start early in the morning.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Valley Ride", location: "Sunny Valley", description: "A scenic valley ride. Traverse through beautiful valleys and enjoy the serene environment on horseback.", tips: "Ensure your horse is well-fed and hydrated.", thingsToTake: "Water, snacks, hat, horse feed.", travelTime: "3 hours", additionalInfo: "Best enjoyed in the cooler hours of the day.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Hilltop Gallop", location: "Highland Hills", description: "A gallop to the hilltop. Experience the thrill of horseback riding while enjoying panoramic views from the hilltop.", tips: "Wear comfortable riding gear. Bring extra water.", thingsToTake: "Water, snacks, riding gear, camera.", travelTime: "2.5 hours", additionalInfo: "Best to start early in the morning.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6)
            ]),
            Level(name: "Medium Trails", description: "Enjoy horseback riding trails", image: "https://i.pinimg.com/564x/17/b2/52/17b252f965f81c806c8281cbfffb7a29.jpg", hikingSpots: [
                HikingSpot(name: "Valley Ride", location: "Sunny Valley", description: "A scenic valley ride. Traverse through beautiful valleys and enjoy the serene environment on horseback.", tips: "Ensure your horse is well-fed and hydrated.", thingsToTake: "Water, snacks, hat, horse feed.", travelTime: "3 hours", additionalInfo: "Best enjoyed in the cooler hours of the day.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Hilltop Gallop", location: "Highland Hills", description: "A gallop to the hilltop. Experience the thrill of horseback riding while enjoying panoramic views from the hilltop.", tips: "Wear comfortable riding gear. Bring extra water.", thingsToTake: "Water, snacks, riding gear, camera.", travelTime: "2.5 hours", additionalInfo: "Best to start early in the morning.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Valley Ride", location: "Sunny Valley", description: "A scenic valley ride. Traverse through beautiful valleys and enjoy the serene environment on horseback.", tips: "Ensure your horse is well-fed and hydrated.", thingsToTake: "Water, snacks, hat, horse feed.", travelTime: "3 hours", additionalInfo: "Best enjoyed in the cooler hours of the day.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Hilltop Gallop", location: "Highland Hills", description: "A gallop to the hilltop. Experience the thrill of horseback riding while enjoying panoramic views from the hilltop.", tips: "Wear comfortable riding gear. Bring extra water.", thingsToTake: "Water, snacks, riding gear, camera.", travelTime: "2.5 hours", additionalInfo: "Best to start early in the morning.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Valley Ride", location: "Sunny Valley", description: "A scenic valley ride. Traverse through beautiful valleys and enjoy the serene environment on horseback.", tips: "Ensure your horse is well-fed and hydrated.", thingsToTake: "Water, snacks, hat, horse feed.", travelTime: "3 hours", additionalInfo: "Best enjoyed in the cooler hours of the day.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Hilltop Gallop", location: "Highland Hills", description: "A gallop to the hilltop. Experience the thrill of horseback riding while enjoying panoramic views from the hilltop.", tips: "Wear comfortable riding gear. Bring extra water.", thingsToTake: "Water, snacks, riding gear, camera.", travelTime: "2.5 hours", additionalInfo: "Best to start early in the morning.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6)
            ]),
            Level(name: "Hard Trails", description: "Enjoy horseback riding trails", image: "https://i.pinimg.com/564x/9c/21/67/9c2167a527ef354c3f7a75ea6bfe6931.jpg", hikingSpots: [
                HikingSpot(name: "Valley Ride", location: "Sunny Valley", description: "A scenic valley ride. Traverse through beautiful valleys and enjoy the serene environment on horseback.", tips: "Ensure your horse is well-fed and hydrated.", thingsToTake: "Water, snacks, hat, horse feed.", travelTime: "3 hours", additionalInfo: "Best enjoyed in the cooler hours of the day.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Hilltop Gallop", location: "Highland Hills", description: "A gallop to the hilltop. Experience the thrill of horseback riding while enjoying panoramic views from the hilltop.", tips: "Wear comfortable riding gear. Bring extra water.", thingsToTake: "Water, snacks, riding gear, camera.", travelTime: "2.5 hours", additionalInfo: "Best to start early in the morning.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Valley Ride", location: "Sunny Valley", description: "A scenic valley ride. Traverse through beautiful valleys and enjoy the serene environment on horseback.", tips: "Ensure your horse is well-fed and hydrated.", thingsToTake: "Water, snacks, hat, horse feed.", travelTime: "3 hours", additionalInfo: "Best enjoyed in the cooler hours of the day.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Hilltop Gallop", location: "Highland Hills", description: "A gallop to the hilltop. Experience the thrill of horseback riding while enjoying panoramic views from the hilltop.", tips: "Wear comfortable riding gear. Bring extra water.", thingsToTake: "Water, snacks, riding gear, camera.", travelTime: "2.5 hours", additionalInfo: "Best to start early in the morning.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6),
                HikingSpot(name: "Valley Ride", location: "Sunny Valley", description: "A scenic valley ride. Traverse through beautiful valleys and enjoy the serene environment on horseback.", tips: "Ensure your horse is well-fed and hydrated.", thingsToTake: "Water, snacks, hat, horse feed.", travelTime: "3 hours", additionalInfo: "Best enjoyed in the cooler hours of the day.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.5),
                HikingSpot(name: "Hilltop Gallop", location: "Highland Hills", description: "A gallop to the hilltop. Experience the thrill of horseback riding while enjoying panoramic views from the hilltop.", tips: "Wear comfortable riding gear. Bring extra water.", thingsToTake: "Water, snacks, riding gear, camera.", travelTime: "2.5 hours", additionalInfo: "Best to start early in the morning.", video: "https://videos.pexels.com/video-files/2040076/2040076-hd_1920_1080_24fps.mp4", image: "https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", rating: 4.6)
            ])
        ])
    ]
}
